kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: himarket-admin
  name: himarket-admin
data:
  HIMARKET_SERVER: "http://himarket-server"
  # 指标服务地址，不设则与 HIMARKET_SERVER 相同
  METRICS_SERVER: "http://himarket-server"